### ISSUE TITLE
Separate NameAndTerm from the drivers

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#101]
In GAME, we use `NameAndTerm` to represent the key of the feature, and it is tightly coupled with both the training and scoring Drivers. However, using _Name_ and _Term_ to represent features is too LinkedIn specific, which makes it difficult to provide a walk through for GAME on some public data (e.g., #76) with formats such as LibSVM.

One proposal is to constrain the usage of `NameAndTerm` to the Avro I/O utility functions, for example, when (i) reading data from an Avro record and (ii) writing model as an Avro record with `NameAndTerm` format. And after stage (i) or before stage (ii), Drivers should be agnostic about the upstream/downstream formats of data and model, respectively.

**Comment by li-ashelkov** [comment]
After #318, this should be resolved
