### ISSUE TITLE
Refactor and add unit tests for AbstractOptimizer

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#104]
Current there is minimal test coverage for `AbstractOptimizer`, which acts as one core piece of Photon's optimization. As a result, I think increasing the test coverage for `AbstractOptimizer` is necessary.

At the same time, `AbstractOptimizer` has too many side-effect related operations and global states, which might cause some of it's components difficult to test, as a result, some refactoring work might be needed as well.

**Comment by ashelkovnykov** [comment]
This issue may be resolved by changes I am working on for #122.

**Comment by ashelkovnykov** [comment]
Optimizer + AbstractOptimizer should be refactored to decouple state tracking code from the Optimizer. Instead state tracking should be implemented as a stacked trait or with event providers + listeners.

@joshvfleming

**Comment by XianXing** [comment]
Related to PR #131.

**Comment by fastier-li** [comment]
131 is merged and class `AbstractOptimizer` does not exist anymore. I am going to close this ticket, but please open another one if there is still something to do in the existing code base. Thanks!
