### ISSUE TITLE
Throw an error if the input record contains features with duplicated name.

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#124]
In function `getFeaturesFromGenericRecord` in `DataProcessingUtils`, we are reading and combining features from different fields for each record.

In some cases, it is possible that two features with same name may appear in different fields of the same record, for example, in an item-to-item recommendation scenario, the same feature (e.g., item category) may appear in both source and destination feature fields, even though they mean different things (e.g., source item's category and destination item's category).

However, currently `getFeaturesFromGenericRecord` converts features with same name but from different fields into the same feature index that is used in both model training and scoring, which may lead to some unexpected model behavior.

In general, it might be useful to throw an error (or warning?) message to let the user aware of such potential problem if more than one features with same name are found while processing the record in `getFeaturesFromGenericRecord`.

**Comment by XianXing** [comment]
@TDDFT suggested one such potential case in job-to-jobs recommendation problem to me.

**Comment by fastier-li** [comment]
That has been fixed for sure. We got a lot of feedback when we turned it on :-) But in the end, we prevailed and people had to clean up their pipelines :-)
