### ISSUE TITLE
Avro data format should be able to automatically tell whether it's TrainingExample.avsc or ResponsePrediction.avsc 

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#132]
Theoretically, we should be able reflect from the input records to get the Avro schemas and then switch data reader functions accordingly.

Previously, this is not a big issue. But after introducing multiple input formats for Photon ML, specifying file format and then specify Avro schema format seems to be redundant.

Another way to solve this is that we could consider retire one of the schema (argument is that those two schemas aren't so different ) or treat one of them as AVRO_XXX input format.

@TDDFT @XianXing:  opinions?

**Comment by XianXing** [comment]
Good suggestion, and I think this is the right direction for Photon.

**Comment by ashelkovnykov** [comment]
The solution to this issue should also make GAME flexible to the type of Avro schema provided (currently it is hard-coded to use ResponsePrediction).

**Comment by li-ashelkov** [comment]
This has been resolved, Photon ML now handles generic column names in DataFrames but has defaults to fall back to.
