### ISSUE TITLE
Make LibSVM format automatically detect feature dimension

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#133]
@XianXing : I'm just about to implement the auto feature dimension scanning and then realized that there is an issue with previous approach I'm thinking about

```
// Like what we are doing in GLMSuite

when #loadLabledPoints method is called, we try to see whether an indexMap is already loaded.
   If yes:
       we use that one.
   If not:
       we scan dataset one more time to figure out the indexMap (or feature dimension in LibSVM's scenario)
```

This approach has a side effect that we are basically assuming indexMapLoader is not gonna be used anywhere before we load training dataset first (and it has to be the training dataset as the 1st dataset we loaded to guarantee that all the indexing is done correctly). Such assumption cannot be derived from trait definitions which made me feel a bit uneasy.

Maybe we should consider introduce an `initialize` method in `InputFormat` and configure the indexMap diligently instead of lazily?

**Comment by timyitong** [comment]
Ah, never mind. Actually I just realized ```IndexMapLoader#prepare``` method is introduced sort of due to this reason. I guess there is indeed a clean way to implement such scanning function.

**Comment by XianXing** [comment]
I saw your reply via email, but couldn't see it posted here.

Can we count the number of features of the data in ```IndexMapLoader#prepare``` as you suggested in the email?

**Comment by timyitong** [comment]
@XianXing : not really, I realized that I cannot do it (so I deleted the post). Because IndexMapLoader should not make any assumption about data format, otherwise, one indexmap might only work with one format. Thus we still if need put the logics in InputFormat if ever needed. One solution might be a method something like:
```
initializeIndexMap(config: Config)
```

But what kinda arguments to leave for the method seems to be a bit tricky. Maybe for now we could still just do it the simple way and assume that we might still have the side effect?

**Comment by XianXing** [comment]
I see, indeed, ```IndexMapLoader ``` is now only used when the input data is in Avro format, and it doesn't make sense to let ```IndexMapLoader#prepare``` to count the number of unique features.

As a result, such process may have to happen somewhere through ```InputDataFormat```, and I agree that having a new method ```initialize``` method for ```InputDataFormat``` should be a good option, or we can even put such logic into a secondary constructor of ```LibSVMInputDataFormat``` as well (if ```AvroInputDataFormat``` doesn't need such as function and we don't want to change ```trueFeatureDimension``` from val to var).

**Comment by joshvfleming** [comment]
@timyitong @XianXing 

I'm currently working on a proposal to reorganize this a little, and I think it might clear up the dimension-detecting problem also.

I'm still fleshing out the details, but in a nutshell:

 * InputDataFormat interface will be renamed to DataReader. This name captures the dual purpose of reading the data from disk and decoding it.
 * There will be a family of DataReaders (e.g. AvroDataReader, LibSVMDataReader, VowpalWabbitDataReader. etc) that extend DataReader (essentially the same arrangement as InputDataFormat).
 * All Avro-specific code will be moved to AvroDataReader
 
The interface is stateless, and looks like this:

| DataReader |
| --- |
| read(path: Path) → (DataFrame, IndexMap) |
| read(path: Path, indexMap: IndexMap) → DataFrame |
| read(path: String) → (DataFrame, IndexMap) |
| read(path: String, indexMap: IndexMap) → DataFrame |

Note that there are two basic possibilities:

 1. We pass in the path and a pre-created index map
 2. We pass in only the path, and an default index map is created for us

Given this background, I think we can solve the auto-dimension problem by making two passes over the data in the "read" function:

1. First pass: Map over items, collect features into a dynamic list for each item, and keep track of the **n**, the number of unique features 
2. Second pass: Map over items, convert each dynamic list into a sparse vector of size **n**

Does this sound reasonable?

**Comment by XianXing** [comment]
Sounds good to me.

**Comment by timyitong** [comment]
@joshvfleming : that's a great plan. Looking forward to the new thing!
