### ISSUE TITLE
Decoupling index map from the driver

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#134]
This is a design issue, also may be related to the bigger theme "decouple the Photon client code from Photon core code".

It looks like the method `indexMapLoader` is not necessary for all types of `InputDataFormat`, because currently the concept of "index map" only exists if the input data is in Avro format, and even for `AvroInputDataFormat` we can initialize the index map as part of the `loadLabeledPoints` function, thus the `indexMapLoader` is not absolutely necessary. 

As a result, decoupling index map from the driver might be helpful, for example, if we decide to add feature hashing based method to Photon (like what [Vowpal Wabbit](https://github.com/JohnLangford/vowpal_wabbit) does).

However, I see that currently the Photon driver is tightly coupled with index maps almost everywhere, e.g. in `writeModelsInText` and all types of diagnostics, so I don't expect any major refactoring that decouples index map from the driver would happen very soon. But let's be mindful and try to reduce the dependency on index maps when adding new components to Photon.

**Comment by timyitong** [comment]
@XianXing good call! If Photon core codes only care about ```LabelPoint```, we could leave the model serialization and LabelPoints loading to others. Then ```InputDataFormat``` don't need to care about ```indexMap``` anymore.

**Comment by fastier-li** [comment]
I'm going to close this, after taking with Josh Fleming: It's done for GAME but not for legacy photon, and we probably won't do any legacy photon refactoring, in favor of internally using a fixed effect GAME model for photon models.
