### ISSUE TITLE
GAME default update-sequence should not be empty 

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#137]
In GAME driver:
```
      val coordinates = updatingSequence.map { coordinateId =>
        val coordinate = dataSets(coordinateId) match {
```

If ```updatingSequence``` is not assigned a default value or made as a required parameter, then coordinates will be an empty collection, GAME will skip everything, without outputting any model info and without errors.

Maybe consider either making the param required or figuring out a good default value before training?

**Comment by XianXing** [comment]
Let's make it a required parameter.

**Comment by XianXing** [comment]
PR is out. I was also trying to update the li-photon-template for GAME accordingly, then realized that  update-sequence is already a required parameter there. Nice work in foreseeing this issue @ashelkovnykov!
