### ISSUE TITLE
Photon does not check for repeated regularization weights

### ISSUE THREAD

**Issue by ashelkovnykov** [linkedin/photon-ml#140]
When regularization is enabled, Photon does not check that each regularization weight is unique. 

Behaviour once Photon finishes training for a repeated regularization weight:
- If the model reached convergence, Photon will run one more iteration for each time the regularization weight is repeated.
- If the model reached the maximum number of iterations, Photon will resume training from where it left off with the same regularization weight until the model converges or the max number of iterations is reached again.

**Comment by ferd36** [comment]
I am on it.
