### ISSUE TITLE
Clean up GAME Evaluators

### ISSUE THREAD

**Issue by ashelkovnykov** [linkedin/photon-ml#144]
The `Evaluator` trait should be split into two traits, and it's descendants in the `com.linkedin.photon.ml.evaluation` package need to be separated into two groups: one group for calculating loss during coordinate descent and one group for selecting the best model. Currently there is an overlap.

Ideally, the `Evaluator` used for choosing between models should be configurable.

The `LocalEvaluator` and `AreaUnderROCCurveLocalEvaluator` are part of an upcoming enhancement to Photon-ML, but are not currently used anywhere.

**Comment by XianXing** [comment]
Looks good.
Just want to add that ```LocalEvaluator``` and ```AreaUnderROCCurveLocalEvaluator``` are used in a separate LinkedIn MP, although they are not used anywhere in Photon-ML.
