### ISSUE TITLE
NameAndTermFeatureSetContainer.main failed on large input data

### ISSUE THREAD

**Issue by TDDFT** [linkedin/photon-ml#148]
When data size is large (e.g. 10+TB), feature NameAndTerm distinct com.linkedin.photon.ml.avro.AvroUtils#readNameAndTermSetFromGenericRecords fails often. We need to change the default distinct partitions to make it stable.

**Comment by XianXing** [comment]
Good suggestion.

Maybe we want to make such ```numPartitions``` parameter for ```distinct``` configurable and expose it to the users, and at the same time set it to a more reasonable default value.
