### ISSUE TITLE
Precision at n evaluation & optimization

### ISSUE THREAD

**Issue by Mschneider93** [linkedin/photon-ml#151]
Hi guys,

I use recommendation systems only with respect to a certain rank. In particular, on the website we can only display 4 recommendations. Would it be possible optimize and to benchmark on "precision @ n"?  

Best,
Michael

**Comment by XianXing** [comment]
Good point, I will look into it and see how can we add precision@n as a new evaluator to GAME.

**Comment by pogil** [comment]
@Mschneider93, do you mean precision@n for an entire dataset, or do you mean the average across context for precision@n on items sharing some context id?

**Comment by XianXing** [comment]
Precision @ k as an evaluator is added to Photon, the next step is to refactor Photon so that different algorithms can call it for evaluation purpose.

**Comment by Mschneider93** [comment]
@XianXing that is awesome I check that out

@pogil good point, having both information can be extremely helpful. precision@n for an entire dataset can be used to justify the overall expect performance. And the precisio@n depending on a specific context helps certainly in communicating with project/context owners.  

Thanks a lot - this is a really awesome project

**Comment by XianXing** [comment]
Precision@K is introduced to Photon-ML through #166.
