### ISSUE TITLE
Add an option in GAME avro that it looks into metadataMap if an randomEffectId is not found in 1st layer field 

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#156]
I'm wondering whether it's an okay to add an option here:
https://github.com/linkedin/photon-ml/blob/3b6bcb8c0211b4bd6fe4e339b14597fde1730283/photon-ml/src/main/scala/com/linkedin/photon/ml/avro/data/DataProcessingUtils.scala#L120

So the suggested behavior is that we firstly look into a particular field for id, if not found, we would try a second time looking into metadataMap.

The major benefit is that then if I want to try out multiple ids, I could easily modify metadaMap field without changing the schema (schema change means either a copy-and-paste-and-mod or some hacky programmed dynamic generation) to add/delete/mod group ids in data preparation jobs.

@XianXing @joshvfleming @ashelkovnykov @TDDFT : would this be a reasonable feature to add? I'd be happy to help check in the codes.

**Comment by XianXing** [comment]
Sounds reasonable to me, at least we are not making the code backward incompatible.

Since @joshvfleming is working on separating the Photon client code (e.g., Avro related stuff) from the Photon core code, he may have some insights on this issue as well.

**Comment by joshvfleming** [comment]
Sounds alright to me. It could be confusing behavior to someone new to the system, though, so we need to make sure it's documented.

**Comment by XianXing** [comment]
So let's do it @timyitong :)

**Comment by ashelkovnykov** [comment]
Sounds reasonable to me - sorry for the late reply, misread some of the code and got myself very confused

**Comment by rrohan** [comment]
+1 This is super useful.

**Comment by timyitong** [comment]
@XianXing @joshvfleming @ashelkovnykov: thanks a lot for all the useful feedback! I'll start checking in the codes. Will pay attention to documentation that we just do this dark magic without explaining.
