### ISSUE TITLE
Outputing weight in the scoring results

### ISSUE THREAD

**Issue by jeyang-li** [linkedin/photon-ml#163]
Hi,

I found that the current scoring flow does not store "weight" of the examples. 
The weights are needed if the evaluation data is weighted. Could you please make scoring flow output weight of the examples?

**Comment by XianXing** [comment]
This requires either
(i) changing the Avro schema  [```ScoringResultAvro.avsc```](https://github.com/linkedin/photon-ml/blob/master/photon-avro-schemas/src/main/avro/ScoringResultAvro.avsc) by adding an additional field "weight";
or (ii) changing the logic of the scoring job such that the user can specify any field they'd like to keep in ```metadataMap```.

**Comment by XianXing** [comment]
@jeyang-li The PR #168 is merged, and you can try it out after we update GAME templates to reflect the change made in the PR.

**Comment by jeyang-li** [comment]
Thank you @XianXing!
