### ISSUE TITLE
Remove dependency on org.apache.spark.Logging

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#189]
One of the breaking changes introduced in [Spark 2.0](https://spark.apache.org/releases/spark-release-2-0-0.html) is that `org.apache.spark.Logging` is removed.

As a result, PhotonML can no longer depend on the logger provided in `org.apache.spark.Logging`.

I did a quick search and found that most of places that depend on  `org.apache.spark.Logging` are legacy PhotonML modules, such as `ModelTraining`, `diagnostics.fitting`, `stat`, etc.

I have the following two proposals:
1. Replace those loggers with the one generated by `org.apache.log4j.Logger.getRootLogger`, basically we use whatever the  root logger is or `org.apache.log4j.Logger.getLogger(this.getClass)` to get a logger for the underlying class. This way is more lightweight.
2. Replace those loggers with `PhotonLogger`, which is more consistent with the new GAME module and our more recent features added to PhotonML, however, this will break some of our current (internal) APIs.

Please let me know which one you would prefer.

**Comment by joshvfleming** [comment]
@XianXing Sorry for the delay getting back to you on this. We're still not sure which direction we want to go with PhotonLogger, so I guess it makes sense to go with option #1 and use the log4j logger in the meantime.

**Comment by XianXing** [comment]
Thanks @joshvfleming. Option 1 sounds good to me.

This is not a blocking issue, but as soon as we have Spark 2.0 compatibility (just compatible, no need to fully migrate to 2.0) with Photon, we will be able to leverage Photon as a library in some of our core products.

**Comment by joshvfleming** [comment]
@XianXing Cool. We're going to try migrating to 2.0 here pretty soon also. The upgrade to 1.6 was pretty rocky because of some issues with how 1.6 manages memory while shuffling on large datasets. Hoping 2.0 will be smoother.

**Comment by joshvfleming** [comment]
@XianXing Fixed here: https://github.com/linkedin/photon-ml/pull/221
