### ISSUE TITLE
IntegTest runtime should be reduced

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#19]
The integTest takes too long for now. @TDDFT made a good point that a majority of them is coming from ObjectveFunctionIntegTest. It's actually also doubled compared to previously since we have scala 2.10, 2.11 crossbuild! We should figure out a way to cut down sampling rate and cut down number of cases to verify.

Personally, I think tests taking too long is affecting productivity.

**Comment by timyitong** [comment]
To add to this, free Travis CI actually will kill process running longer than 120 minutes. Its VM resources are much less than our dev boxes or laptops, so everything is slower. This actually could become an issue to auto builds.

**Comment by XianXing** [comment]
PR #48 reduces the integTest runtime, and Travis CI works with the integTests again.

**Comment by XianXing** [comment]
Re-open this issue, because we identified a few other places that the run time for integTest can be further reduced without decreasing the test coverage.
