### ISSUE TITLE
Why cannot find the model-diagnostic.html file after finishing my job?

### ISSUE THREAD

**Issue by PayneJoe** [linkedin/photon-ml#196]
HI all , I am new here ,I just launched my first job "demo_photon_ml_logistic_regression", it seemed to be worked , as I checked the three result files under folder "out" which were respectively named "best-model-text" , "learned-models-text" , and "log-message.txt" , but I did not  find the "model-diagnostic.html" file under the folder out. Am I missed something ?

**Comment by zhenchuan** [comment]
try to add the `  --diagnostic-mode ALL ` param when using spark-submit

**Comment by PayneJoe** [comment]
thanks for the tip

**Comment by XianXing** [comment]
Thanks for helping out @zhenchuan :)
