### ISSUE TITLE
Output directory cleaning after consecutive runs of the same GAME training workflow

### ISSUE THREAD

**Issue by cagriozcaglar** [linkedin/photon-ml#207]
I ran a GAME training job, which first failed with error, resulting in intermediate files in the output folder. After fixing the error and rerunning the job, the job failed due to this error: 

... modelingPipeline/best/model-spec for client <ip address> already exists`

For this workflow, `delete.output.dir.if.exists` parameter is set to true by default, so I was expecting the output folder to be deleted at the beginning of the execution. I was wondering if this is the case still, or if this file referenced in the error message above is an exclusion to directory cleaning for GAME training jobs.

**Comment by fastier-li** [comment]
This parameter controls the removal of the HDFS directory set in parameter outputDir. See [code here](https://github.com/linkedin/photon-ml/blob/4be25936220155bf121751f9f9661f1d4ae62abf/photon-client/src/main/scala/com/linkedin/photon/ml/cli/game/training/Driver.scala#L48).

The code doesn't seem to show exceptions - everything in `output-dir` will be deleted, as far as I can tell, if `delete-output-dir-if-exists` is set to true... and you reach that point in the `Driver` code. There shouldn't be an exception.

**Comment by fastier-li** [comment]
I am going to close this issue for now. Please let us know if it happens again. Thanks!

**Comment by cagriozcaglar** [comment]
I see. We went through this item earlier with Ankan, and resolved the issue.

Thanks,
Cagri
