### ISSUE TITLE
Tutorial source missing

### ISSUE THREAD

**Issue by sbourke** [linkedin/photon-ml#223]
The code which is run in the docker image is not part of the github repo. Is it possible to make this public to better understand what is happening.

**Comment by fastier-li** [comment]
We have an upcoming work item to work on documentation and tutorials.

**Comment by fastier-li** [comment]
@sbourke - note though that the code for e.g. `RunPhoton` and `Data` is not really interesting: `RunPhoton` is merely a "main" that does nothing but read arguments, parse them, and call the Game code that's available in this repo. I doubt you would learn much from that "main" itself.

**Comment by sbourke** [comment]
Hi @fastier-li  thanks - I did get everything working in the end and it was useful in terms of getting to know the codebase. Would have been slightly easier to jump through the steps of the main!

**Comment by fastier-li** [comment]
@sbourke - great! I'll close this item for now. Thanks!
