### ISSUE TITLE
GAME might also want to leverage IndexMap interfaces

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#24]
So that we could bring in offheap map seemlessly.

**Comment by XianXing** [comment]
@timyitong Do you have plan to bring the offheap map to GAME? If not, I will help and make it happen.

**Comment by joshvfleming** [comment]
I'm picking this one up.

**Comment by timyitong** [comment]
@joshvfleming @XianXing : please go ahead. I'm afraid I don't enough time to do this.

**Comment by XianXing** [comment]
Solution is proposed in PR #160.
