### ISSUE TITLE
I have a question about the model

### ISSUE THREAD

**Issue by chenchunyu88** [linkedin/photon-ml#253]
Does it support random effect with a design matrix, say y=Xb+ Wa+e, where W is the design matrix for random effect a? Or does it support relationship matrix for random effects, say y=Xb+a+e, where a~N(0,A*sigma2). Thank you

**Comment by fastier-li** [comment]
Hi chenchunyu88 - can you be more specific about the terms in your equations? We are not sure what `e` or `A` refer to for example. Thanks!  

You can also take a look at the GLMix paper referenced at the bottom of our main github page: [KDD paper](http://www.kdd.org/kdd2016/papers/files/adf0562-zhangA.pdf)

**Comment by fastier-li** [comment]
Chenchunyu88 - a complement my answer above - GAME supports both of the models, you mention. The "normal" mode is to supply training data for the random effects, but it is possible to train the random effects without specifying features, which should essentially be your second option.

**Comment by chenchunyu88** [comment]
Thanks for replying. Let me make my question more clear. 
For **y**=**Xb**+**Wg**+**e**, **Xb** is the fixed effects, **g** is the random effect, **W** is the incidence matrix for random effects **g**, **e** is the residual. **W** can be dense matrix [[0,1,2],[1,1,0],[0,0,2]], for example. 

And for the second one, **y**=**Xb**+**a**+**e**, others are the same except vector **a** is random effects that is multivariate normal distributed with mean **0** and variance provided by covariance matrix **A**, i.e., **a**~N(0,**A**).

I am kind of interested in if photon-ml handles these complex models.

@fastier-li  Thanks

**Comment by fastier-li** [comment]
@chenchunyu88 - is my previous answer good enough for you? Or should we go into more details?
