### ISSUE TITLE
Compiled avro classes isn't showing up in integTest folder in Idea IntelliJ

### ISSUE THREAD

**Issue by timyitong** [linkedin/photon-ml#26]
We probably need to figure out what's proper configuration to include the compiled classes into IntelliJ's configuration.

**Comment by XianXing** [comment]
I don't know a solution neither, and any insights on this issue would be greatly appreciated!

**Comment by fastier-li** [comment]
I believe this has been fixed. I can see inside our compiled jars in IntelliJ, but the trick is to "Add as Library..." (right click menu when pointing to the jar) on the jar. When I look at the photon-all jar, I find the avro compiled classes in there, and I can look at them in IntelliJ. 

I'm going to close this issue for now, send me an email if this is still a problem. Thanks!
