### ISSUE TITLE
The validateDataFrame function pulls entire dataset into Driver

### ISSUE THREAD

**Issue by joshvfleming** [linkedin/photon-ml#306]
The following code attempts to pull the entire dataset into the Driver before running validations:

https://github.com/linkedin/photon-ml/blob/237c315d9b78945c5c0d5dbafae31ebcfeef58a1/photon-client/src/main/scala/com/linkedin/photon/ml/data/DataValidators.scala#L265

We should instead map over the DataFrame rows so that the validations run in a distributed fasion, and then `collect` the results.

**Comment by li-ashelkov** [comment]
Resolve by #307
