### ISSUE TITLE
Example of a Mixed effects model?

### ISSUE THREAD

**Issue by skanskan** [linkedin/photon-ml#431]
Hello.

I would like to use Photon-ml to fit a logistic regression model with mixed effects but I couldn't find any coded example, just theoretical formulas.

Could you please provide it?
For example I have a csv file:

ID 	City 	Year	Age 	Weight 	Sex 	Treatment
1   AA  	2005	23   	65		F		Y
1   AA  	2007	25   	65		F		Y
2	BB		1999	45		88		M		N
...

If I wanted to use R I would do:
mydata <- fread("myfile.csv")
glmer(Treatment~Year+Age+Weight+Sex+(1|City/ID),data=mydata,family = "binomial", REML=F)
This assumes random effects for the person nested withing each city.

How can I get the same results usung photon-ML?

**Comment by cmjiang** [comment]
Hi,
Photon ML does not support CSV format. You can convert your data format to Avro and follow the [tutorial](https://github.com/linkedin/photon-ml/wiki/Photon-ML-Tutorial) for the toy example.

**Comment by skanskan** [comment]
I've read all that tutorials but there isn't any code solving an example, just theory, diagrams.

**Comment by joshvfleming** [comment]
@skanskan The last 3 sections of the notebook that @cmjiang linked to all involve training mixed effect models (with code).

**Comment by skanskan** [comment]
Is there any way to read it without installing docker on my computer?
