### ISSUE TITLE
Examples for hyperparameter tuning

### ISSUE THREAD

**Issue by qingquansong** [linkedin/photon-ml#471]
Can we add some examples for using RandomSearch and BayesianOptimization functions to tune the GLMix models? Thanks!

**Comment by cmjiang** [comment]
Hi @qingquansong,
BayesianOptimization is no longer supported in Photon ML at this moment. The PR https://github.com/linkedin/photon-ml/pull/454 aims at removing hyperparameter autotuning in this repo. Grid search is still supported as the default tuning method.

**Comment by qingquansong** [comment]
Thanks for the reply! Another examples for grid search? I saw that we can set a list of regularization parameter directly. But is that all we can tune?

**Comment by cmjiang** [comment]
Yes, that list is about a grid search. Once you specify a list of the regularization, a list of the models in the same length will be trained and you can find the best model in the output.

**Comment by yunboouyang** [comment]
Just want to mention that you can specify regularization weights for each component of GLMix, such that [1, 2] for a fixed effects model, [1, 10] for a per-member model and [1, 100] for a per-job model. In this case photon-ml will do cross products and train 8 models in total.

**Comment by qingquansong** [comment]
> Just want to mention that you can specify regularization weights for each component of GLMix, such that [1, 2] for a fixed effects model, [1, 10] for a per-member model and [1, 100] for a per-job model. In this case photon-ml will do cross products and train 8 models in total.

Thanks for the clarification!
