### ISSUE TITLE
Add Matrix Factorization to GAME

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#58]
Matrix factorization fits naturally to the GAME framework, and adding matrix factorization to GAME is a promising direction to model the interaction among the effects in the latent space.

Since adding matrix factorization to GAME may require some non-trivial amount of work, I'd like to break down this issue to several smaller tasks/issues and address them sequentially with corresponding PRs.

**Comment by fastier-li** [comment]
I believe this is complete? If it is note, please open a new ticket with details of what still needs to be done. Thanks!
