### ISSUE TITLE
Functions in AvroUtils and AvroIOUtils are duplicated

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#66]
Some functions in `AvroUtils` and `AvroIOUtils` are duplicated, such as `readAvroFiles` in `AvroUtils` and `readFromAvro` in `AvroIOUtils`.

**Comment by fastier-li** [comment]
I'm going to fix this today. Thanks!

**Comment by fastier-li** [comment]
Fixed in PR 246.

**Comment by fastier-li** [comment]
Fix was merged. We reached a compromise for now where one function calls the other, and the functions are side by side to make it easier to look at them. In the future, we think further refactorings will just make both functions disappear altogether. Thanks!
