### ISSUE TITLE
No data validators are available for GAME

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#75]
For Photon's GLM model training, different generalized linear algorithms are equipped with different data validators in `DataValidators` that perform sanity checks for the input data.

At the same time, No data validators are available for GAME. It would be useful if GAME can leverage some of the existing data validators built for GLM, and add a few more validators at the feature's level, such as checking whether duplicated features exist for each input data point.

**Comment by li-ashelkov** [comment]
Resolved by #300
