### ISSUE TITLE
Decouple Avro specific functions/classes from the rest of Photon-ML

### ISSUE THREAD

**Issue by XianXing** [linkedin/photon-ml#8]
Currently Avro is tightly coupled with Photon-ML, especially through various type of drivers, as well as the use of "name-term-value" to represent the features.

In order to make Photon-ML more friendly to a wider audience, it's useful to decouple Avro specific functions/classes from the rest of Photon-ML.

We can discuss what are the possible short vs. long solutions.

**Comment by timyitong** [comment]
This PR is one step towards this issue: https://github.com/linkedin/photon-ml/pull/126
   as we are easing the input format assumption for the simple linear model driver .

**Comment by fastier-li** [comment]
@XianXing - is this still an issue we need to look at? Please let me know - we might work on it soon.

**Comment by XianXing** [comment]
I think recent refactoring (client/core/lib) on Photon should be related to the idea proposed here, basically we'd like to make sure Photon is not restricted to Avro serialized/formatted data.

But you guys have more context than me now, so please feel free to close this issue once the client/core/lib refactoring is done (is it done already?).

**Comment by fastier-li** [comment]
Yes, the refactoring is done. We'll talk about internally about other
formats than Avro before I close this ticket, and I'll post the outcome
here. Thanks!

Thanks,

Frank

**Comment by fastier-li** [comment]
The "master plan" is to provide a library of data readers for various format that would all feed `GameEstimator.fit` with `DataFrames` and ancillary data structures. This is already exemplified by `[AvroDataReader](https://github.com/linkedin/photon-ml/blob/8702fea9a436d4979a3e672fe20ae30e32078f43/photon-client/src/main/scala/com/linkedin/photon/ml/data/AvroDataReader.scala)`. 

I'm going improve on the recent client refactoring by isolating `AvroDataReader` in an `avro` package, and colocate in that package the model writer too. We can then have parallel modules for `parquet` ... and others.

**Comment by ashelkovnykov** [comment]
While we don't have support for Parquet or LIBSVM data in the client code, sufficient decoupling has been done. For a while now, the input to the `GameEstimator` has been a `DataFrame` with features stored as `Vector` objects.

For that reason, I am going to close this issue and separate ones can be opened for adding specific kinds of readers derived from `DataReader`.
